
title: Tristan Cook
description: >- # this means to ignore newlines until "baseurl:"
  Personal site for Tristan Cook. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed